### ISSUE TITLE
Pin clearance issue near R49

### ISSUE THREAD

**Issue by AdamElsharhawy** [proveskit/battery_board#5]
Since the battery holder pin near R49 needs to be soldered in, there is a possible short/clearance issue if not carefully soldered during assembly. 
![image](https://github.com/proveskit/battery_board/assets/38268419/cd41f1bc-e759-4727-a08d-3aa9ab0ca77d)

**Comment by Mikefly123** [comment]
Got it, that pin and that resistor are definitely too close for comfort. If we do a V3c battery board we'll definitely try and fix this. 

@PragunB we should also move to try and document this in the assembly guide as a potential risk.

**Comment by Mikefly123** [comment]
This will be fixed in V3c

<img width="819" alt="Screenshot 2024-07-16 at 6 23 02 PM" src="https://github.com/user-attachments/assets/54a725d9-fb8d-4524-9fa7-d5a35b2f64d7">
